name: ocr_scan_text
description: OCR Scan Text is a wrapper around the "Google ML kit Text Recognition" library.
version: 1.3.1
homepage: https://github.com/devmuhammadreda/ocr_scan_text

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.1
  image: ^4.5.2
  pdf_render: ^1.4.12
  path: ^1.9.0
  path_provider: ^2.1.5
  file_picker: ^8.3.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boursorama.ocr_scan_text.ocr_scan_text
        pluginClass: OcrScanTextPlugin
      ios:
        pluginClass: OcrScanTextPlugin
